name: Update Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

